# Generated by Django 3.1 on 2020-08-10 13:48

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', max_length=18)),
                ('alignment', models.PositiveIntegerField(default=0)),
                ('cohesion', models.PositiveIntegerField(default=0)),
                ('separation', models.PositiveIntegerField(default=0)),
                ('max_force', models.PositiveIntegerField(default=0)),
                ('max_speed', models.PositiveIntegerField(default=0)),
                ('min_amount', models.PositiveIntegerField(default=1)),
                ('max_amount', models.PositiveIntegerField(default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
